from collections import Counter
from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from api.app.models.api import CatalogSummaryOut, InventoryLotOut
from api.app.models.db import CatalogItem, InventoryLot, Store
from api.app.services.utils import new_id


async def list_catalog_items(session: AsyncSession) -> list[CatalogItem]:
    return (await session.execute(select(CatalogItem).order_by(CatalogItem.brand, CatalogItem.product_name))).scalars().all()


async def get_catalog_item(session: AsyncSession, item_id: str) -> CatalogItem | None:
    return await session.get(CatalogItem, item_id)


async def merge_catalog_metadata(session: AsyncSession, item: CatalogItem, patch: dict[str, object]) -> CatalogItem:
    item.metadata_json = {**dict(item.metadata_json or {}), **patch}
    await session.flush()
    return item


async def catalog_summary(session: AsyncSession) -> CatalogSummaryOut:
    store_count = await session.scalar(select(func.count(Store.id)))
    items = (await session.execute(select(CatalogItem))).scalars().all()
    units = await session.scalar(select(func.coalesce(func.sum(InventoryLot.quantity_on_hand), 0)))
    return CatalogSummaryOut(
        sku_count=len(items),
        supplier_count=len({item.supplier_name for item in items}),
        store_count=store_count or 0,
        inventory_units=units or 0,
    )


async def inventory_for_catalog_item(
    session: AsyncSession,
    catalog_item_id: str,
    lot_codes: list[str] | None = None,
    states: list[str] | None = None,
) -> list[InventoryLotOut]:
    stmt = (
        select(InventoryLot, Store)
        .join(Store, Store.id == InventoryLot.store_id)
        .where(InventoryLot.catalog_item_id == catalog_item_id)
        .order_by(Store.state, Store.city)
    )
    rows = (await session.execute(stmt)).all()
    lot_set = {lot.strip().lower() for lot in lot_codes or [] if lot.strip()}
    state_set = {state.strip().upper() for state in states or [] if state.strip()}
    output: list[InventoryLotOut] = []
    for lot, store in rows:
        if lot_set and (lot.lot_code or "").strip().lower() not in lot_set:
            continue
        if state_set and store.state.upper() not in state_set:
            continue
        output.append(
            InventoryLotOut(
                id=lot.id,
                catalog_item_id=lot.catalog_item_id,
                store_id=store.id,
                store_name=store.name,
                city=store.city,
                state=store.state,
                latitude=store.latitude,
                longitude=store.longitude,
                lot_code=lot.lot_code,
                quantity_on_hand=lot.quantity_on_hand,
                last_seen_at=lot.last_seen_at,
            )
        )
    return output


async def ensure_catalog_bootstrap(session: AsyncSession) -> None:
    count = await session.scalar(select(func.count(CatalogItem.id)))
    if count:
        return

    stores = [
        Store(id="store_sf", name="Northstar Market Noe", city="San Francisco", state="CA", region="West", latitude=37.7516, longitude=-122.4350),
        Store(id="store_oak", name="Northstar Market Oakland", city="Oakland", state="CA", region="West", latitude=37.8044, longitude=-122.2712),
        Store(id="store_bk", name="Northstar Market Williamsburg", city="Brooklyn", state="NY", region="Northeast", latitude=40.7081, longitude=-73.9571),
        Store(id="store_jer", name="Northstar Market Jersey City", city="Jersey City", state="NJ", region="Northeast", latitude=40.7178, longitude=-74.0431),
        Store(id="store_atl", name="Northstar Market Midtown", city="Atlanta", state="GA", region="South", latitude=33.7838, longitude=-84.3839),
        Store(id="store_col", name="Northstar Market Short North", city="Columbus", state="OH", region="Midwest", latitude=39.9788, longitude=-83.0030),
        Store(id="store_dal", name="Northstar Market Knox", city="Dallas", state="TX", region="South", latitude=32.8218, longitude=-96.7877),
        Store(id="store_chi", name="Northstar Market Wicker Park", city="Chicago", state="IL", region="Midwest", latitude=41.9105, longitude=-87.6776),
        Store(id="store_la", name="Northstar Market Silver Lake", city="Los Angeles", state="CA", region="West", latitude=34.0928, longitude=-118.2807),
        Store(id="store_sea", name="Northstar Market Capitol Hill", city="Seattle", state="WA", region="West", latitude=47.6245, longitude=-122.3208),
        Store(id="store_den", name="Northstar Market LoDo", city="Denver", state="CO", region="Mountain", latitude=39.7530, longitude=-104.9990),
        Store(id="store_phx", name="Northstar Market Arcadia", city="Phoenix", state="AZ", region="Southwest", latitude=33.5092, longitude=-112.0719),
        Store(id="store_mia", name="Northstar Market Brickell", city="Miami", state="FL", region="South", latitude=25.7617, longitude=-80.1918),
        Store(id="store_bos", name="Northstar Market Back Bay", city="Boston", state="MA", region="Northeast", latitude=42.3505, longitude=-71.0763),
        Store(id="store_phl", name="Northstar Market Rittenhouse", city="Philadelphia", state="PA", region="Northeast", latitude=39.9496, longitude=-75.1669),
        Store(id="store_msp", name="Northstar Market North Loop", city="Minneapolis", state="MN", region="Midwest", latitude=44.9847, longitude=-93.2793),
        Store(id="store_pdx", name="Northstar Market Pearl", city="Portland", state="OR", region="West", latitude=45.5290, longitude=-122.6819),
        Store(id="store_clt", name="Northstar Market South End", city="Charlotte", state="NC", region="South", latitude=35.2138, longitude=-80.8571),
    ]
    session.add_all(stores)

    items = [
        CatalogItem(
            id="cat_fbj_sesame_single",
            sku="FBJ-NOODLE-SESAME-SINGLE",
            brand="Fly By Jing",
            product_name="Creamy Sesame Noodles Single Pack",
            upc="850052239886",
            category="instant noodles",
            supplier_name="Fly By Jing",
            co_manufacturer_name="Third-party noodle manufacturer",
            ingredients_json=["wheat noodles", "sesame paste", "soy sauce", "chili oil"],
            allergens_json=["wheat", "soy", "sesame"],
            supplier_aliases_json=["Fly by Jing", "Fly By Jing"],
            metadata_json={"channels": ["retail", "online"], "store_states": ["CA", "NY", "TX"], "catalog_source": "bootstrap"},
        ),
        CatalogItem(
            id="cat_fbj_sauce",
            sku="FBJ-SAUCE-CHILI-CRISP",
            brand="Fly By Jing",
            product_name="Sichuan Chili Crisp Sauce",
            upc="850052239022",
            category="sauce",
            supplier_name="Fly By Jing",
            co_manufacturer_name=None,
            ingredients_json=["chili", "soybean oil", "mushroom powder", "sesame oil"],
            allergens_json=["soy", "sesame"],
            supplier_aliases_json=["Fly by Jing", "Fly By Jing"],
            metadata_json={"channels": ["retail"], "store_states": ["CA", "IL"], "catalog_source": "bootstrap"},
        ),
        CatalogItem(
            id="cat_kroger_croutons",
            sku="KRO-CROUTON-CHEESE-GARLIC",
            brand="Kroger",
            product_name="Homestyle Cheese Garlic Croutons 5 oz",
            upc="011110813534",
            category="croutons",
            supplier_name="Sugar Foods LLC",
            co_manufacturer_name="Sugar Foods LLC",
            ingredients_json=["wheat flour", "cheese garlic seasoning", "milk powder", "salt"],
            allergens_json=["wheat", "milk"],
            supplier_aliases_json=["Sugar Foods", "Sugar Foods LLC", "Solina USA", "California Dairies Inc."],
            metadata_json={"channels": ["grocery"], "store_states": ["GA", "OH", "IL"], "catalog_source": "bootstrap"},
        ),
        CatalogItem(
            id="cat_ns_croutons",
            sku="NS-CROUTON-GARLIC-PARM",
            brand="Northstar",
            product_name="Garlic Parmesan Croutons",
            upc="744000110427",
            category="croutons",
            supplier_name="Northstar Private Label Snacks",
            co_manufacturer_name="Sugar Foods LLC",
            ingredients_json=["wheat flour", "parmesan seasoning", "milk powder", "garlic"],
            allergens_json=["wheat", "milk"],
            supplier_aliases_json=["Sugar Foods LLC", "Solina USA"],
            metadata_json={"private_label": True, "store_states": ["NY", "NJ", "CA"], "catalog_source": "bootstrap"},
        ),
        CatalogItem(
            id="cat_gg_snackmix",
            sku="GG-SNACKMIX-SAVORY",
            brand="Good & Gather",
            product_name="Sweet and Savory Snack Mix",
            upc="085239901134",
            category="snack mix",
            supplier_name="John B. Sanfilippo & Son, Inc.",
            co_manufacturer_name="John B. Sanfilippo & Son, Inc.",
            ingredients_json=["pretzels", "seasoned nuts", "powdered milk", "spices"],
            allergens_json=["milk", "wheat", "tree nuts"],
            supplier_aliases_json=["JBSS", "California Dairies Inc."],
            metadata_json={"channels": ["grocery"], "store_states": ["CA", "WA"], "catalog_source": "bootstrap"},
        ),
        CatalogItem(
            id="cat_leafy_greens",
            sku="NS-PRODUCE-SPINACH",
            brand="Northstar Farms",
            product_name="Organic Baby Spinach",
            upc="744000220102",
            category="produce",
            supplier_name="Central Valley Greens",
            co_manufacturer_name=None,
            ingredients_json=["spinach"],
            allergens_json=[],
            supplier_aliases_json=[],
            metadata_json={"private_label": True, "store_states": ["CA"], "catalog_source": "bootstrap"},
        ),
        CatalogItem(
            id="cat_ghirardelli_cocoa",
            sku="GHI-COCOA-DOUBLE-CHOC",
            brand="Ghirardelli",
            product_name="Double Chocolate Premium Hot Cocoa Mix",
            upc=None,
            category="powdered drink mixes",
            supplier_name="Ghirardelli Chocolate Company",
            co_manufacturer_name=None,
            ingredients_json=["cocoa", "sugar", "dry milk", "powdered milk"],
            allergens_json=["milk"],
            supplier_aliases_json=["Ghirardelli", "Ghirardelli Chocolate", "California Dairies Inc.", "California Dairies"],
            metadata_json={"channels": ["grocery"], "store_states": ["CA", "WA", "CO", "AZ", "FL", "MA"], "catalog_source": "bootstrap"},
        ),
        CatalogItem(
            id="cat_great_value_pizza",
            sku="GV-PIZZA-RISING-CRUST",
            brand="Great Value",
            product_name="Rising Crust Pepperoni Pizza",
            upc=None,
            category="frozen pizza",
            supplier_name="Walmart Private Brands",
            co_manufacturer_name=None,
            ingredients_json=["wheat flour", "mozzarella cheese", "tomato sauce", "milk powder"],
            allergens_json=["milk", "wheat"],
            supplier_aliases_json=["Great Value", "Walmart", "California Dairies Inc.", "California Dairies"],
            metadata_json={"channels": ["grocery"], "store_states": ["CA", "TX", "IL", "PA", "NC"], "catalog_source": "bootstrap"},
        ),
        CatalogItem(
            id="cat_zapps_voodoo_chips",
            sku="ZAP-VOODOO-CHIPS",
            brand="Zapp's",
            product_name="Voodoo Potato Chips",
            upc=None,
            category="potato chips",
            supplier_name="Utz Brands",
            co_manufacturer_name=None,
            ingredients_json=["potatoes", "vegetable oil", "seasoning blend", "whey powder"],
            allergens_json=["milk"],
            supplier_aliases_json=["Zapp's", "Zapps", "Utz", "Utz Brands", "California Dairies Inc."],
            metadata_json={"channels": ["grocery"], "store_states": ["GA", "FL", "NC", "TX", "PA"], "catalog_source": "bootstrap"},
        ),
        CatalogItem(
            id="cat_kars_trail_mix",
            sku="KARS-SWEET-SALTY-MIX",
            brand="Kar's",
            product_name="Sweet 'n Salty Trail Mix",
            upc=None,
            category="trail mix",
            supplier_name="Second Nature Brands",
            co_manufacturer_name=None,
            ingredients_json=["peanuts", "raisins", "sunflower kernels", "milk chocolate candies"],
            allergens_json=["milk", "peanuts", "tree nuts"],
            supplier_aliases_json=["Kar's", "Kars", "Second Nature Brands"],
            metadata_json={"channels": ["grocery"], "store_states": ["OH", "MI", "IL", "MN", "PA"], "catalog_source": "bootstrap"},
        ),
        CatalogItem(
            id="cat_david_sunflower_seeds",
            sku="DAVID-SUNFLOWER-ORIGINAL",
            brand="David",
            product_name="Original Sunflower Seeds",
            upc=None,
            category="sunflower seeds",
            supplier_name="Conagra Brands",
            co_manufacturer_name=None,
            ingredients_json=["sunflower seeds", "salt"],
            allergens_json=[],
            supplier_aliases_json=["David", "Conagra", "Conagra Brands"],
            metadata_json={"channels": ["grocery"], "store_states": ["CA", "AZ", "CO", "TX"], "catalog_source": "bootstrap"},
        ),
        CatalogItem(
            id="cat_organic_valley_eggs",
            sku="OV-LARGE-BROWN-EGGS",
            brand="Organic Valley",
            product_name="Large Brown Eggs",
            upc=None,
            category="eggs",
            supplier_name="Organic Valley",
            co_manufacturer_name=None,
            ingredients_json=["eggs"],
            allergens_json=["eggs"],
            supplier_aliases_json=["Organic Valley", "CROPP Cooperative"],
            metadata_json={"channels": ["grocery"], "store_states": ["CA", "WA", "OR", "NY", "MA", "PA"], "catalog_source": "bootstrap"},
        ),
        CatalogItem(
            id="cat_365_walnuts",
            sku="365-ORGANIC-WALNUTS",
            brand="365 by Whole Foods Market",
            product_name="Organic Walnut Halves and Pieces",
            upc=None,
            category="walnuts",
            supplier_name="Whole Foods Market",
            co_manufacturer_name=None,
            ingredients_json=["organic walnuts"],
            allergens_json=["tree nuts"],
            supplier_aliases_json=["Whole Foods", "Whole Foods Market", "365"],
            metadata_json={"channels": ["grocery"], "store_states": ["CA", "NY", "NJ", "MA", "PA"], "catalog_source": "bootstrap"},
        ),
        CatalogItem(
            id="cat_dole_cantaloupe_chunks",
            sku="DOLE-CANTALOUPE-CHUNKS",
            brand="Dole",
            product_name="Cantaloupe Chunks",
            upc=None,
            category="cantaloupe",
            supplier_name="Dole Fresh Produce",
            co_manufacturer_name=None,
            ingredients_json=["cantaloupe"],
            allergens_json=[],
            supplier_aliases_json=["Dole", "Dole Fresh Produce"],
            metadata_json={"channels": ["grocery"], "store_states": ["CA", "AZ", "CO", "TX", "FL"], "catalog_source": "bootstrap"},
        ),
        CatalogItem(
            id="cat_wawona_peach_slices",
            sku="WAWONA-FROZEN-PEACHES",
            brand="Wawona",
            product_name="Frozen Peach Slices",
            upc=None,
            category="peaches",
            supplier_name="Wawona Frozen Foods",
            co_manufacturer_name=None,
            ingredients_json=["peaches"],
            allergens_json=[],
            supplier_aliases_json=["Wawona", "Wawona Frozen Foods"],
            metadata_json={"channels": ["grocery"], "store_states": ["CA", "WA", "OR", "AZ"], "catalog_source": "bootstrap"},
        ),
        CatalogItem(
            id="cat_raw_farm_cheddar",
            sku="RAWFARM-RAW-CHEDDAR",
            brand="Raw Farm",
            product_name="Raw Milk Cheddar Cheese",
            upc=None,
            category="dairy cheese",
            supplier_name="Raw Farm",
            co_manufacturer_name=None,
            ingredients_json=["raw milk", "cheese", "salt", "cultures"],
            allergens_json=["milk"],
            supplier_aliases_json=["Raw Farm", "Raw Farm LLC"],
            metadata_json={"channels": ["grocery"], "store_states": ["CA", "WA", "OR", "AZ"], "catalog_source": "bootstrap"},
        ),
        CatalogItem(
            id="cat_spring_mulberry_bar",
            sku="SM-CHOCOLATE-BAR",
            brand="Spring & Mulberry",
            product_name="Date-Sweetened Chocolate Bar",
            upc=None,
            category="chocolate bars",
            supplier_name="Spring & Mulberry",
            co_manufacturer_name=None,
            ingredients_json=["cocoa", "dates", "cocoa butter"],
            allergens_json=[],
            supplier_aliases_json=["Spring & Mulberry", "Spring and Mulberry"],
            metadata_json={"channels": ["grocery"], "store_states": ["NY", "NJ", "MA", "PA", "CA"], "catalog_source": "bootstrap"},
        ),
        CatalogItem(
            id="cat_diamond_shruumz_bar",
            sku="DIAMOND-SHRUUMZ-DARK-CHOC",
            brand="Diamond Shruumz",
            product_name="Dark Chocolate Bar",
            upc=None,
            category="mushroom chocolate",
            supplier_name="Prophet Premium Blends",
            co_manufacturer_name="Prophet Premium Blends",
            ingredients_json=["chocolate", "mushroom blend"],
            allergens_json=[],
            supplier_aliases_json=["Diamond Shruumz", "Prophet Premium Blends"],
            metadata_json={"channels": ["grocery"], "store_states": ["CA", "NY", "FL", "TX", "IL"], "catalog_source": "bootstrap"},
        ),
        CatalogItem(
            id="cat_ghirardelli_chocolate_bar",
            sku="GHI-DARK-CHOCOLATE-BAR",
            brand="Ghirardelli",
            product_name="Dark Chocolate Bar",
            upc=None,
            category="chocolate bars",
            supplier_name="Ghirardelli Chocolate Company",
            co_manufacturer_name=None,
            ingredients_json=["cocoa", "sugar", "cocoa butter"],
            allergens_json=[],
            supplier_aliases_json=["Ghirardelli", "Ghirardelli Chocolate"],
            metadata_json={"channels": ["grocery"], "store_states": ["CA", "WA", "CO", "AZ", "FL", "MA"], "catalog_source": "bootstrap"},
        ),
        CatalogItem(
            id="cat_ghirardelli_powdered_drinks",
            sku="GHI-POWDERED-DRINK-MIXES",
            brand="Ghirardelli",
            product_name="Powdered Drink Mixes",
            upc=None,
            category="powdered drink mixes",
            supplier_name="Ghirardelli Chocolate Company",
            co_manufacturer_name=None,
            ingredients_json=["cocoa", "sugar", "dry milk", "powdered milk"],
            allergens_json=["milk"],
            supplier_aliases_json=["Ghirardelli", "Ghirardelli Chocolate", "California Dairies Inc.", "California Dairies"],
            metadata_json={"channels": ["grocery"], "store_states": ["CA", "WA", "CO", "AZ", "FL", "MA"], "catalog_source": "bootstrap"},
        ),
        CatalogItem(
            id="cat_parents_choice_rice_cereal",
            sku="PC-RICE-BABY-CEREAL",
            brand="Parent's Choice",
            product_name="Rice Baby Cereal",
            upc=None,
            category="baby food",
            supplier_name="Walmart Private Brands",
            co_manufacturer_name=None,
            ingredients_json=["rice flour", "vitamins", "minerals"],
            allergens_json=[],
            supplier_aliases_json=["Parent's Choice", "Parents Choice", "Walmart"],
            metadata_json={"channels": ["grocery"], "store_states": ["CA", "TX", "IL", "GA", "OH"], "catalog_source": "bootstrap"},
        ),
        CatalogItem(
            id="cat_black_sheep_eggs",
            sku="BSE-BROWN-EGGS",
            brand="Black Sheep Egg Company",
            product_name="Eggs",
            upc=None,
            category="eggs",
            supplier_name="Black Sheep Egg Company",
            co_manufacturer_name=None,
            ingredients_json=["eggs"],
            allergens_json=["eggs"],
            supplier_aliases_json=["Black Sheep Egg Company"],
            metadata_json={"channels": ["grocery"], "store_states": ["CA", "OR", "WA"], "catalog_source": "bootstrap"},
        ),
        CatalogItem(
            id="cat_sun_hong_enoki",
            sku="SUNHONG-ENOKI-MUSHROOMS",
            brand="Sun Hong Foods",
            product_name="Enoki Mushrooms",
            upc=None,
            category="mushrooms",
            supplier_name="Sun Hong Foods, Inc.",
            co_manufacturer_name=None,
            ingredients_json=["enoki mushrooms"],
            allergens_json=[],
            supplier_aliases_json=["Sun Hong Foods", "Sun Hong Foods Inc."],
            metadata_json={"channels": ["grocery"], "store_states": ["CA", "NY", "NJ", "PA"], "catalog_source": "bootstrap"},
        ),
        CatalogItem(
            id="cat_fulvic_care_powder_tablets",
            sku="FULVIC-CARE-POWDER-TABLETS",
            brand="Fulvic Care",
            product_name="Powder and Tablets",
            upc=None,
            category="supplements",
            supplier_name="Fulvic Care",
            co_manufacturer_name=None,
            ingredients_json=["fulvic mineral powder"],
            allergens_json=[],
            supplier_aliases_json=["Fulvic Care"],
            metadata_json={"channels": ["grocery", "wellness"], "store_states": ["CA", "NY", "FL", "TX"], "catalog_source": "bootstrap"},
        ),
        CatalogItem(
            id="cat_felix_smoked_seafood",
            sku="FELIX-SMOKED-SEAFOOD",
            brand="Felix Custom Smoking",
            product_name="Seafood Products",
            upc=None,
            category="seafood",
            supplier_name="Felix Custom Smoking",
            co_manufacturer_name=None,
            ingredients_json=["smoked seafood"],
            allergens_json=["fish", "shellfish"],
            supplier_aliases_json=["Felix Custom Smoking", "Felix Custom Smoking Seafood"],
            metadata_json={"channels": ["grocery"], "store_states": ["WA", "OR", "CA"], "catalog_source": "bootstrap"},
        ),
        CatalogItem(
            id="cat_little_hatch_ready_to_eat",
            sku="LITTLE-HATCH-RTE-FOODS",
            brand="Little Hatch's",
            product_name="Ready To Eat Foods",
            upc=None,
            category="ready-to-eat foods",
            supplier_name="Little Hatch's",
            co_manufacturer_name=None,
            ingredients_json=["prepared foods"],
            allergens_json=[],
            supplier_aliases_json=["Little Hatch's", "Little Hatchs"],
            metadata_json={"channels": ["grocery"], "store_states": ["TX", "AZ", "CO"], "catalog_source": "bootstrap"},
        ),
        CatalogItem(
            id="cat_nutramigen_formula",
            sku="NUTRAMIGEN-HYPO-FORMULA",
            brand="Nutramigen",
            product_name="Hypoallergenic Powdered Infant Formula Products",
            upc=None,
            category="infant formula",
            supplier_name="Reckitt Mead Johnson",
            co_manufacturer_name="Mead Johnson",
            ingredients_json=["powdered infant formula"],
            allergens_json=["milk"],
            supplier_aliases_json=["Nutramigen", "Mead Johnson", "Reckitt"],
            metadata_json={"channels": ["grocery"], "store_states": ["CA", "NY", "TX", "IL", "FL"], "catalog_source": "bootstrap"},
        ),
        CatalogItem(
            id="cat_diamond_shruumz_chocolate_bars",
            sku="DIAMOND-SHRUUMZ-CHOCOLATE-BARS",
            brand="Diamond Shruumz",
            product_name="Chocolate Bars",
            upc=None,
            category="mushroom chocolate",
            supplier_name="Prophet Premium Blends",
            co_manufacturer_name="Prophet Premium Blends",
            ingredients_json=["chocolate", "mushroom blend"],
            allergens_json=[],
            supplier_aliases_json=["Diamond Shruumz", "Prophet Premium Blends"],
            metadata_json={"channels": ["grocery"], "store_states": ["CA", "NY", "FL", "TX", "IL"], "catalog_source": "bootstrap"},
        ),
        CatalogItem(
            id="cat_diamond_shruumz_gummies",
            sku="DIAMOND-SHRUUMZ-GUMMIES",
            brand="Diamond Shruumz",
            product_name="Gummies",
            upc=None,
            category="mushroom gummies",
            supplier_name="Prophet Premium Blends",
            co_manufacturer_name="Prophet Premium Blends",
            ingredients_json=["gummies", "mushroom blend"],
            allergens_json=[],
            supplier_aliases_json=["Diamond Shruumz", "Prophet Premium Blends"],
            metadata_json={"channels": ["grocery"], "store_states": ["CA", "NY", "FL", "TX"], "catalog_source": "bootstrap"},
        ),
        CatalogItem(
            id="cat_diamond_shruumz_cones",
            sku="DIAMOND-SHRUUMZ-CONES",
            brand="Diamond Shruumz",
            product_name="Cones",
            upc=None,
            category="mushroom cones",
            supplier_name="Prophet Premium Blends",
            co_manufacturer_name="Prophet Premium Blends",
            ingredients_json=["cones", "mushroom blend"],
            allergens_json=[],
            supplier_aliases_json=["Diamond Shruumz", "Prophet Premium Blends"],
            metadata_json={"channels": ["grocery"], "store_states": ["CA", "NY", "FL"], "catalog_source": "bootstrap"},
        ),
        CatalogItem(
            id="cat_spring_mulberry_select_bars",
            sku="SM-SELECT-CHOCOLATE-BARS",
            brand="Spring & Mulberry",
            product_name="Select Chocolate Bars",
            upc=None,
            category="chocolate bars",
            supplier_name="Spring & Mulberry",
            co_manufacturer_name=None,
            ingredients_json=["cocoa", "dates", "cocoa butter"],
            allergens_json=[],
            supplier_aliases_json=["Spring & Mulberry", "Spring and Mulberry"],
            metadata_json={"channels": ["grocery"], "store_states": ["NY", "NJ", "MA", "PA", "CA"], "catalog_source": "bootstrap"},
        ),
        CatalogItem(
            id="cat_sour_cream_onion_cheese_curds",
            sku="CHEESE-CURDS-SOUR-CREAM-ONION",
            brand="Westby Cooperative Creamery",
            product_name="Sour Cream and Onion Cheese Curds",
            upc=None,
            category="cheese curds",
            supplier_name="Westby Cooperative Creamery",
            co_manufacturer_name=None,
            ingredients_json=["cheese", "milk", "sour cream and onion seasoning"],
            allergens_json=["milk"],
            supplier_aliases_json=["Westby Cooperative Creamery"],
            metadata_json={"channels": ["grocery"], "store_states": ["WI", "IL", "MN"], "catalog_source": "bootstrap"},
        ),
        CatalogItem(
            id="cat_white_cheddar_seasoning",
            sku="GRIFFITH-WHITE-CHEDDAR-SEASONING",
            brand="Griffith Foods",
            product_name="White Cheddar Seasoning Products",
            upc=None,
            category="seasoning",
            supplier_name="Griffith Foods",
            co_manufacturer_name="Griffith Foods",
            ingredients_json=["white cheddar seasoning", "milk powder"],
            allergens_json=["milk"],
            supplier_aliases_json=["Griffith Foods"],
            metadata_json={"channels": ["grocery"], "store_states": ["IL", "OH", "PA", "NY"], "catalog_source": "bootstrap"},
        ),
    ]
    session.add_all(items)

    lot_specs = [
        ("cat_fbj_sesame_single", "store_sf", "FBJ-SESAME-A", 18),
        ("cat_fbj_sesame_single", "store_bk", "FBJ-SESAME-B", 22),
        ("cat_fbj_sesame_single", "store_dal", "FBJ-SESAME-C", 14),
        ("cat_fbj_sauce", "store_sf", "SAUCE-0426", 40),
        ("cat_fbj_sauce", "store_chi", "SAUCE-0526", 31),
        ("cat_kroger_croutons", "store_atl", "KRO-CROUTON-A", 36),
        ("cat_kroger_croutons", "store_col", "KRO-CROUTON-B", 28),
        ("cat_kroger_croutons", "store_chi", "KRO-CROUTON-C", 19),
        ("cat_ns_croutons", "store_bk", "L0426", 46),
        ("cat_ns_croutons", "store_jer", "L0426", 39),
        ("cat_ns_croutons", "store_sf", "L0501", 24),
        ("cat_gg_snackmix", "store_sf", "MAY0526", 33),
        ("cat_gg_snackmix", "store_oak", "MAY0526", 21),
        ("cat_leafy_greens", "store_sf", "SPIN-0519", 72),
        ("cat_ghirardelli_cocoa", "store_la", "COCOA-0526-A", 38),
        ("cat_ghirardelli_cocoa", "store_sea", "COCOA-0526-B", 24),
        ("cat_ghirardelli_cocoa", "store_den", "COCOA-0526-C", 19),
        ("cat_great_value_pizza", "store_chi", "PIZZA-0526-IL", 27),
        ("cat_great_value_pizza", "store_dal", "PIZZA-0526-TX", 31),
        ("cat_great_value_pizza", "store_clt", "PIZZA-0526-NC", 22),
        ("cat_zapps_voodoo_chips", "store_mia", "ZAP-0526-FL", 46),
        ("cat_zapps_voodoo_chips", "store_atl", "ZAP-0526-GA", 34),
        ("cat_zapps_voodoo_chips", "store_phl", "ZAP-0526-PA", 29),
        ("cat_kars_trail_mix", "store_msp", "TRAIL-0426-MN", 41),
        ("cat_kars_trail_mix", "store_chi", "TRAIL-0426-IL", 33),
        ("cat_kars_trail_mix", "store_col", "TRAIL-0426-OH", 28),
        ("cat_david_sunflower_seeds", "store_phx", "SUN-0426-AZ", 52),
        ("cat_david_sunflower_seeds", "store_den", "SUN-0426-CO", 37),
        ("cat_organic_valley_eggs", "store_bos", "EGG-0625-MA", 64),
        ("cat_organic_valley_eggs", "store_bk", "EGG-0625-NY", 58),
        ("cat_organic_valley_eggs", "store_pdx", "EGG-0625-OR", 49),
        ("cat_365_walnuts", "store_jer", "WAL-1125-NJ", 21),
        ("cat_365_walnuts", "store_bos", "WAL-1125-MA", 26),
        ("cat_dole_cantaloupe_chunks", "store_phx", "MELON-0825-AZ", 44),
        ("cat_dole_cantaloupe_chunks", "store_dal", "MELON-0825-TX", 39),
        ("cat_wawona_peach_slices", "store_la", "PEACH-0825-CA", 35),
        ("cat_wawona_peach_slices", "store_pdx", "PEACH-0825-OR", 25),
        ("cat_raw_farm_cheddar", "store_sf", "RAW-0326-CA", 18),
        ("cat_raw_farm_cheddar", "store_la", "RAW-0326-LA", 22),
        ("cat_spring_mulberry_bar", "store_bk", "SM-1225-NY", 36),
        ("cat_spring_mulberry_bar", "store_phl", "SM-1225-PA", 19),
        ("cat_diamond_shruumz_bar", "store_mia", "DS-0725-FL", 14),
        ("cat_diamond_shruumz_bar", "store_dal", "DS-0725-TX", 17),
        ("cat_ghirardelli_chocolate_bar", "store_den", "GHI-BAR-1225-CO", 43),
        ("cat_ghirardelli_chocolate_bar", "store_bos", "GHI-BAR-1225-MA", 29),
        ("cat_ghirardelli_powdered_drinks", "store_la", "GHI-DRINK-0526-CA", 26),
        ("cat_ghirardelli_powdered_drinks", "store_sea", "GHI-DRINK-0526-WA", 18),
        ("cat_parents_choice_rice_cereal", "store_dal", "PC-RICE-0426-TX", 34),
        ("cat_parents_choice_rice_cereal", "store_chi", "PC-RICE-0426-IL", 27),
        ("cat_black_sheep_eggs", "store_pdx", "BSE-0426-OR", 48),
        ("cat_black_sheep_eggs", "store_sea", "BSE-0426-WA", 42),
        ("cat_sun_hong_enoki", "store_sf", "ENOKI-0426-CA", 32),
        ("cat_sun_hong_enoki", "store_bk", "ENOKI-0426-NY", 24),
        ("cat_fulvic_care_powder_tablets", "store_mia", "FULVIC-0426-FL", 15),
        ("cat_fulvic_care_powder_tablets", "store_bk", "FULVIC-0426-NY", 11),
        ("cat_felix_smoked_seafood", "store_sea", "FELIX-SEA-0426-WA", 19),
        ("cat_felix_smoked_seafood", "store_pdx", "FELIX-SEA-0426-OR", 16),
        ("cat_little_hatch_ready_to_eat", "store_dal", "LH-RTE-0426-TX", 29),
        ("cat_little_hatch_ready_to_eat", "store_phx", "LH-RTE-0426-AZ", 23),
        ("cat_nutramigen_formula", "store_chi", "NUTRA-0426-IL", 21),
        ("cat_nutramigen_formula", "store_mia", "NUTRA-0426-FL", 17),
        ("cat_diamond_shruumz_chocolate_bars", "store_la", "DS-BARS-0426-CA", 22),
        ("cat_diamond_shruumz_chocolate_bars", "store_bk", "DS-BARS-0426-NY", 18),
        ("cat_diamond_shruumz_gummies", "store_mia", "DS-GUM-0426-FL", 20),
        ("cat_diamond_shruumz_gummies", "store_dal", "DS-GUM-0426-TX", 16),
        ("cat_diamond_shruumz_cones", "store_sf", "DS-CONE-0426-CA", 14),
        ("cat_spring_mulberry_select_bars", "store_bk", "SM-SEL-1225-NY", 24),
        ("cat_spring_mulberry_select_bars", "store_phl", "SM-SEL-1225-PA", 21),
        ("cat_sour_cream_onion_cheese_curds", "store_chi", "CURD-1225-IL", 28),
        ("cat_sour_cream_onion_cheese_curds", "store_msp", "CURD-1225-MN", 24),
        ("cat_white_cheddar_seasoning", "store_col", "WCHED-1225-OH", 31),
        ("cat_white_cheddar_seasoning", "store_phl", "WCHED-1225-PA", 26),
    ]
    session.add_all(
        InventoryLot(
            id=new_id("lot"),
            catalog_item_id=item_id,
            store_id=store_id,
            lot_code=lot_code,
            quantity_on_hand=quantity,
        )
        for item_id, store_id, lot_code, quantity in lot_specs
    )
    await session.flush()


def supplier_counts(items: list[CatalogItem]) -> Counter[str]:
    return Counter(item.supplier_name for item in items)
